version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - node

  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    ports:
      - "8080:3000"
    volumes:
      - ./node:/usr/src/app
    environment:
      NODE_ENV: production
