version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    build: ./node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=fullcycle
    depends_on:
      - mysql

  mysql:
    image: arm64v8/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
