version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - node

  node:
    build:
      context: ./node
    ports:
      - "8080:3000"
    volumes:
      - ./node:/usr/src/app
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DB: db
    depends_on:
      - mysql

  mysql:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
