FROM node:15 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# RUN npm run build

FROM node:15

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

EXPOSE 3000

CMD ["node", "index.js"]
